### ISSUE TITLE
Import .geojson should have better feedback when it fails to import

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-tasking-manager2#698]
when importing a geojson file, if it fails to import there is no dialog of any sort, it is just silent. some sort of feedback that it actually did fail and maybe why it failed to import would be helpful.

**Comment by ethan-nelson** [comment]
It looks like this is because there is a javascript variable that isn't defined.

`project.new.js:217 `
`Uncaught ReferenceError: pleaseProvideGeojsonOrKmlFileI18n is not defined`

**Comment by pgiraud** [comment]
@ethan-nelson good catch.
I missed this when cherry-picking a commit from @pyrog in https://github.com/hotosm/osm-tasking-manager2/pull/521

**Comment by ethan-nelson** [comment]
Fixed in #727. The translation is now correctly defined and will throw a visible error to the user about the bad import (rather than the javascript failing silently due to an undefined variable).

**Comment by bgirardot** [comment]
I still do not get an error message as far as I can see in firefox.

**Comment by ethan-nelson** [comment]
Hmmm, I got an error now when uploading a wrong file type, so we're at least part of the way there:

![error](https://cloud.githubusercontent.com/assets/8998918/16364325/08e100de-3baa-11e6-81f9-4790074f6ed6.PNG)

**Comment by ethan-nelson** [comment]
https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/templates/project.new.mako#L30 missing `I18n` in variable name to match the error called in https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/static/js/project.new.js#L98
